In [1]:
import numpy as np

In [13]:
a=np.array([[10,12,14,16,18],[20,22,24,26,28],[30,32,34,36,38],[40,42,44,46,48],[50,47,45,43,41]])

In [15]:
a.shape

(5, 5)

In [30]:
a[a> 30] = -1

In [31]:
print(a)

[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [35]:
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [36]:
b.ndim

2

In [37]:
b.shape

(4, 4)

In [38]:
print(type(b))

<class 'numpy.ndarray'>


In [6]:
import pandas as pd

In [7]:
a=pd.Series([10,20,30,40,50])

In [9]:
print(type(a))

<class 'pandas.core.series.Series'>


In [24]:
df=pd.read_csv('sales.csv')

In [25]:
print(df.head(10))

   OrderID       Product  Quantity  Price  Revenue        Date Region
0      101  Mobile Phone         2    500     1000  2025-07-01  North
1      102        Laptop         1   1200     1200  2025-07-01  South
2      103    Headphones         5     50      250  2025-07-02   East
3      104        Tablet         3    300      900  2025-07-03   West
4      105   Smart Watch         4    200      800  2025-07-03  North
5      106        Camera         2    800     1600  2025-07-04  South
6      107      Keyboard         6     40      240  2025-07-04   East
7      108       Monitor         2    150      300  2025-07-05   West
8      109       Printer         1    250      250  2025-07-05  North
9      110         Mouse        10     20      200  2025-07-06  South


In [29]:
print(df.sort_values(by='Revenue')) #sorting

    OrderID       Product  Quantity  Price  Revenue        Date Region
11      112       Charger         8     15      120  2025-07-07   West
9       110         Mouse        10     20      200  2025-07-06  South
10      111      Speakers         3     70      210  2025-07-06   East
6       107      Keyboard         6     40      240  2025-07-04   East
8       109       Printer         1    250      250  2025-07-05  North
2       103    Headphones         5     50      250  2025-07-02   East
7       108       Monitor         2    150      300  2025-07-05   West
4       105   Smart Watch         4    200      800  2025-07-03  North
3       104        Tablet         3    300      900  2025-07-03   West
0       101  Mobile Phone         2    500     1000  2025-07-01  North
1       102        Laptop         1   1200     1200  2025-07-01  South
5       106        Camera         2    800     1600  2025-07-04  South


In [57]:
data={'Name':['Alice','Bob','Kevin','Bilha','Aneesa'],'Department':['Sales','Marketing','Hardware','Software','Programming'],'Salary':[10000,20000,30000,40000,50000],'Age':[21,22,24,23,22]}

In [67]:
g=pd.DataFrame(data)

In [69]:
g=pd.read_csv('Salaries.csv')

In [70]:
g.rename(columns={'Name':'Full Name'},inplace=True) 

In [ ]:
g.to_csv('Sa